version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clients
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: 
      context: ../template-hexagonal-arch 
      dockerfile: Dockerfile
    container_name: java_api
    restart: always
    depends_on:
      - mysql
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh mysql:3306 -- java -jar app.jar"]
    ports:
      - "8080:8080"

volumes:
  mysql_data:
